name: test

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/test.yml'
      - '**.go'
      - 'go.*'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/test.yml'
      - '**.go'
      - 'go.*'

permissions:
  contents: read

jobs:
  go:
    strategy:
      matrix:
        go-version:
          - "1.21"
          - "1.22"
          - "1.23"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install libheif-dev

      - name: Run tests
        run: |
          go test -v ./...
